on:
  push:
    tags:
    - 'v*'

name: Build Mobirise Extension

jobs:
  build:
    name: Create Downloadable Mobirise Extension
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
      - name: Create Mobirise Extension File
        run: |
          cd src/
          zip -r ../witsec-mermaid.mbrext .
          cd ../
      - name: Create Release and Upload Asset
        uses: softprops/action-gh-release@v2
        with:
          files: witsec-mermaid.mbrext
          name: Release ${{ github.ref_name }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
